name: Build and Distribute Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create distribution
        run: |
          mkdir dist
          rsync -av \
            --exclude-from='.distignore' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='dist' \
            . dist/

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r distribution.zip .

      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: distribution.zip

      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./distribution.zip
          asset_name: distribution.zip
          asset_content_type: application/zip
