name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@5a55e811a46f1ac4946dbd337b74ea7f23ebe014 # main
    with:
      minimum-php: "7.4"
      matrix: '{ "exclude": [{ "os": "windows-latest" }] }'
