name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@4c37c47e01b5d1fe256edf40de33454d8bee37d4 # main
    with:
      minimum-php: "7.4"
      matrix: '{ "exclude": [{ "os": "windows-latest" }] }'
